name: nptyping

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          invoke install .[complete]

      - name: Test
        run: invoke test

      - name: Doctest
        run: invoke doctest

      - name: Coverage
        run: |
            invoke coverage
            codecov

      - name: Pylint
        run: invoke pylint

      - name: Style
        run: invoke format --check

  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coverage Report
        uses: codecov/codecov-action@v1
